### ISSUE TITLE
Albert Odyssey - Unreliable saving, losing data

### ISSUE THREAD

**Issue by quidamphx** [srg320/Saturn_MiSTer#17]
### Version (or build number)

231018

### Single or Dual SDRAM?

Single (128MB)

### Steps to reproduce

Play Game
Save Data at Save Point In-Game
Open OSD
Save Backup RAM
Reboot MiSTer
Load Save Data In-Game

### Expected Behavior

Reliable saving

### Actual Behavior

When playing Albert Odyssey using the v1.00 USA BIOS, I'll open the OSD and select Save Backup RAM. After a reboot of the MiSTer, sometimes it will have saved, sometimes not. I've tried rotating through multiple saves spots, overwriting, etc and it seems to happen without a pattern. Most of the time it didn't save correctly. The date/time is also incorrect as the BIOS settings aren't saved when loading a disc.

**Comment by quidamphx** [comment]
I've been trying to narrow this down and I might have figured out what's going on.

Sometimes it seems to be saving as boot.sav (the BIOS) and other times it's saving under the game name. Having to manually load the BIOS each time could be related, maybe once it's auto-detected it will only save under the game file.

From what I can tell, there's no way to save the BIOS data (date/time) but it still created a 64kb boot.sav

I'll do some further testing to see if I make sure to ALWAYS load the BIOS first, and then the game, if it saves reliably. It could be that when doing game then BIOS, it saves under boot.sav

**Comment by Kuba-J** [comment]
There is no need to manually load the bios, the bios should be named boot.rom , it loads automatically then. Save in Albert Odyssey works fine for me every time. If anyone is still suggesting using boot.bin etc this is out of date.

**Comment by Kuba-J** [comment]
https://github.com/MiSTer-unstable-nightlies/Saturn_MiSTer/releases/download/unstable-builds/Saturn_unstable_20240126_1481d9.rbf here is the latest test core.

**Comment by quidamphx** [comment]
Thanks, that's what I came to discover.

Boot.bin was my issue; since plopping boot.rom into the folder, it seems to be working better.

Things change so fast that it's easy to follow something outdated but with testing this morning I went straight to the GitHub page to redo setup and was like heeeeeyyyy.

One thing to note as well, it wasn't working for me to have boot.rom on the SD card while my games were on USB. I generally keep BIOS and system files on the MiSTer SD card but this one didn't agree with it.

Going to close the issue if my problems are solved in a couple of hours, but it's looking good.

**Comment by Kuba-J** [comment]
Boot.rom must always be in the folder where the games are located.

**Comment by quidamphx** [comment]
> There is no need to manually load the bios, the bios should be named boot.rom , it loads automatically then. Save in Albert Odyssey works fine for me every time. If anyone is still suggesting using boot.bin etc this is out of date.

Have you managed to have the date/time set and retained for Albert Odyssey?

**Comment by Kuba-J** [comment]
Time does not work properly in core

**Comment by quidamphx** [comment]
> Time does not work properly in core

Thanks for all your help. Turns out the bug was just a setup issue from an outdated guide.
