### ISSUE TITLE
Attract mode bug in Virtual On (USA)

### ISSUE THREAD

**Issue by gleek12** [srg320/Saturn_MiSTer#19]
### Version (or build number)

20231018

### Single or Dual SDRAM?

Single (128MB)

### Steps to reproduce

In attract mode of Virtual On (USA), for some reason, the demo ALWAYS defaults to the exact same virtualoids and arena on every loop, while on original hardware, it always will play a different, random set of virtualiods and arenas. 

### Expected Behavior

Every time the attact mode loads a demo fight, it should be a random selection of virtualoids and arena.

### Actual Behavior

The attract mode ALWAYS defaults to the exact same virtualoids and arena on every loop

**Comment by Kuba-J** [comment]
Cannot reproduce, core 20240307, works fine

**Comment by gleek12** [comment]
This issue is fixed in the current builds.  I reported this bug based on a much older release version.
