### ISSUE TITLE
Antonio builds wont boot games. 4 chip RAM issue? 

### ISSUE THREAD

**Issue by douglie007** [srg320/Saturn_MiSTer#5]
I have an Antonio build and the RAM chip uses 4 chips, and the only thing I can do with the build right now is load the bios,  if I load a game it locks up on the Sega Saturn logo.  after doing the boot animation.  Is this fixable?

**Comment by srg320** [comment]
#1

**Comment by douglie007** [comment]
Thank you! Understandable.
