### ISSUE TITLE
Death Crimson has vertical lines on the screen

### ISSUE THREAD

**Issue by Krathoon** [srg320/Saturn_MiSTer#8]
### Version (or build number)

20230829

### Single or Dual SDRAM?

Single (128MB)

### Steps to reproduce

Just start up Death Crimson and you get the lines right away.

### Expected Behavior

Just no vertical lines covering the screen.

### Actual Behavior

There are a bunch of sequential white lines covering the screen.

**Comment by thehughhefner** [comment]
The core is still a work in progress and read me explicitly mentions that "do not report any bugs". Close this ticket
